### ISSUE TITLE
Weird compiler error

### ISSUE THREAD

**Issue by m-thread** [manub/scalatest-embedded-kafka#10]
Hi

I am trying to use the 0.4.3-kafka09 release and I get this really weird error when building my tests with maven.
`[ERROR] error: missing or invalid dependency detected while loading class file 'KafkaUnavailableException.class'.
[INFO] Could not access type RuntimeException in package scala.package,
[INFO] because it (or its dependencies) are missing. Check your build definition for
[INFO] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[INFO] A full rebuild may help if 'KafkaUnavailableException.class' was compiled against an incompatible version of scala.package.
`
Have you seen this before? I'm building with Scala 2.11.6 using Scala Maven plugin 3.2.0

**Comment by manub** [comment]
Hi,

No I haven't. I'm currently away with no laptop access but when I'm back next week I'll try to have a look. Are you able to access the RuntimeException class from your project?

**Comment by m-thread** [comment]
Can it be related to me building with 2.11.x and the release is built on 2.10.x?

**Comment by manub** [comment]
There is a 2.11.x available as well. If you're using 2.11 you should use
the 2.11 artifact.

**Comment by m-thread** [comment]
Good point. But it still fails with the same issue :( It's probably something on my side.

**Comment by m-thread** [comment]
Hi again. I managed to get things to work. It turned out that I had to use 2.11.7 in my build to get things to work. I used 2.11.6 before and that gave me the compiler error.

Cheers
/Fredrik

**Comment by manub** [comment]
Thanks for the update Frederik!

**Comment by stanislav-chetvertkov** [comment]
Had the same issue, thanks for the solution

**Comment by prayagupd** [comment]
Make sure scalaVersion the [embedded-kafka is compiled against](https://github.com/manub/scalatest-embedded-kafka/blob/master/build.sbt#L13) is same as the version you are using in your project. With the latest embedded-kafka, it works for `2.11.7`, but not `2.11.5`.
