### ISSUE TITLE
Zk Client fails to connect to Embedded Zk Server in second connection

### ISSUE THREAD

**Issue by raduchilom** [manub/scalatest-embedded-kafka#11]
My use case is something like this:

EmbeddedKafka.start()
createTopic
pushMessages
check messages
EmbeddedKafka.stop()

In the first test it all works well, but in the second test that does something similar to the first one it fails because the Zk client cannot connect to Zk server. You can see the error below. My guess is that the stop method doesn't clean up. Can you please give me some directions with this ?

11/04/2016 11:13:56.277 -  - WARN  o.a.z.ClientCnxn - Session 0x15404611b1e0001 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_60]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_60]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar:3.4.6-1569965]

**Comment by manub** [comment]
Do you `start() and `stop()` in every test? Have you got a gist you could share? I start and stop the Embedded ZK multiple times in the tests and I don't seem to have that problem. Possibly you're not restarting the connection to ZK in every test? Just throwing out ideas, a gist could help me in helping you.

**Comment by raduchilom** [comment]
Thanks. The Zk client was not reinitialised for each restart.
