### ISSUE TITLE
Custom Consumer not working

### ISSUE THREAD

**Issue by kthristov** [manub/scalatest-embedded-kafka#113]
Hi,

I'm struggling to make a custom consumer work. For some reason the just aren't reading from Kafka. I tried with the kafkaConsumer implemented and also making a KafkaConsumer but any of them is reading. The thing is the functions like  consumeFirstStringMessageFrom work perfectly fine. Even copying pasting test are already done in the test folder aren't working...

Im testing with an empty project having just a single test in order to discard not compatible dependencies and still... 

I don't know if doing something wrong or just there is some issue. I'm attaching my test if you can give me some feedback i would really apreciate it.

Thanks.

///////////////////////////////////////////////////////////////////////////////////////////

import java.util.Collections

import scala.collection.JavaConverters._
import net.manub.embeddedkafka.{EmbeddedKafka, EmbeddedKafkaConfig}
import org.apache.kafka.clients.consumer.{ConsumerConfig, KafkaConsumer}
import org.apache.kafka.common.serialization.{StringDeserializer, StringSerializer}
import org.scalatest.{BeforeAndAfterAll, FunSuite, WordSpec}
import java.util.Properties

import org.apache.kafka.clients.producer.{KafkaProducer, ProducerConfig, ProducerRecord}

class KafkaIntegrationTest extends  WordSpec
        with EmbeddedKafka
        with BeforeAndAfterAll{
    
    override def beforeAll(): Unit = {
        super.beforeAll()
        EmbeddedKafka.start()
    }
    
    override def afterAll(): Unit = {
        EmbeddedKafka.stop()
        super.afterAll()
    }
    
    "the publishToKafka method" should {
        "publish synchronously a String message to Kafka" in {
            implicit val serializer: StringSerializer = new StringSerializer()
            implicit val deserializer: StringDeserializer = new StringDeserializer()
            
            val message = "hello world!"
            val topic = "publish_test_topic"
            
            // WORKS FINE
            val producer = new KafkaProducer[String, String](
                Map[String, Object](
                    ProducerConfig.BOOTSTRAP_SERVERS_CONFIG -> ("localhost:" + 6001),
                    ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG -> classOf[
                            StringSerializer].getName,
                    ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG -> classOf[
                            StringSerializer].getName
                ).asJava)
            
            producer.send(new ProducerRecord[String, String](topic, message))
            producer.flush()

            // NOT WORKING
//            val consumer = kafkaConsumer
//            consumer.subscribe(List(topic).asJava)
//            val records = consumer.poll(100)
//            consumer.close()
//

            // NOT WORKING
            val properties =  Map[String, Object](
                ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG -> "localhost:6001",
                ConsumerConfig.GROUP_ID_CONFIG -> "embedded-kafka-spec",
                ConsumerConfig.AUTO_OFFSET_RESET_CONFIG -> "earliest",
                ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG ->
                        classOf[StringDeserializer].getName ,
                ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG ->
                        classOf[StringDeserializer].getName,
                ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG -> "false"
            ).asJava
    
            
            val consumer = new KafkaConsumer[String, String](properties, deserializer, deserializer)
            consumer.subscribe( Collections.singleton(topic) )
            val records = consumer.poll(100)
            consumer.close()
            
            println(records.iterator().hasNext)// should be true
            
            // WORKS PERFECTLY FINE
            producer.send(new ProducerRecord[String, String](topic, message))
            producer.flush()
            
            print(consumeFirstStringMessageFrom(topic))
            producer.close()
            
        }
    }
}

**Comment by ametrocavich** [comment]
Did you figure this out? I seem to be having a very similar issue.
