### ISSUE TITLE
Schema Registry 

### ISSUE THREAD

**Issue by copmir** [manub/scalatest-embedded-kafka#115]
Hi,

It' is possible to extend the EmbeddedKafkaStreamsAllInOne  trait to instantiate a mocked schemaregistry too ?

I'd like to do tests with avro...

Many thx

**Comment by francescopellegrini** [comment]
Hi, 
this has been asked before in #29 and I agree with @manub: Schema Registry is not a core feature of Kafka.

FYI I'm currently working on extending this library to provide such functionality but I'd need some tweaks of hooks to make it work better: maybe I can use this thread to ask for them..
What do you think, @manub?

**Comment by manub** [comment]
I'd be more than happy to see a PR, provided it's disabled by default as I previously suggested.

**Comment by francescopellegrini** [comment]
I'm actually working on a separate library that makes use of this one, since a lot of (non-BC) changes to the APIs would be required in order to provide a PR...
What do you think about changing, e.g., `EmbeddedKafkaSupport.withRunningKafka` `body` param type into `EmbeddedK => T`?

**Comment by francescopellegrini** [comment]
I managed to create the PR you requested, @manub. I'd be pleased to open a discussion on it.

**Comment by francescopellegrini** [comment]
Should this change deserve a version bump? Readme file on `master` branch still refers to 1.1.0...
