### ISSUE TITLE
Evaluate using Apache test utils for Kafka Streams

### ISSUE THREAD

**Issue by francescopellegrini** [manub/scalatest-embedded-kafka#116]
[See KIP-247](https://cwiki.apache.org/confluence/display/KAFKA/KIP-247%3A+Add+public+test+utils+for+Kafka+Streams) and [official documentation](https://kafka.apache.org/11/documentation/streams/developer-guide/testing).

Could it take place of some homebrewed classes or method?

**Comment by manub** [comment]
Yes - would that mean relying on those utils in the `kafka-stream` module or remove it in its entirety? I haven't touched that one, as it was a contribution from @adamosloizou

**Comment by francescopellegrini** [comment]
It would require some small changes to the `kafka-streams` module, but I think keeping the loan pattern would be nice for end-users.
I'll work on a PR in the next days.

**Comment by francescopellegrini** [comment]
After further investigation I found that Apache test library completely mocks the broker and doesn't use ZooKeeper at all, so it could replace this library completely if it weren't for being Java-level verbose and not extensible (Schema Registry requires ZooKeeper and Kafka broker to be found on real ports).
