### ISSUE TITLE
Map vs Properties usages

### ISSUE THREAD

**Issue by francescopellegrini** [manub/scalatest-embedded-kafka#118]
There are mixed usages of `Map[String, Object]` and `java.util.Properties` spread in the codebase to pass configuration to `KafkaConsumer`s, `KafkaProducer`s and so on: is there a reason?

**Comment by manub** [comment]
Not a particular one. I'd like to stick to using `Map` everywhere if possible.

**Comment by manub** [comment]
True but most developers are more familiar with `Map` in my opinion. I'd happily merge a PR!
