### ISSUE TITLE
build failure after sbt import

### ISSUE THREAD

**Issue by thesharpside** [manub/scalatest-embedded-kafka#13]
building with 2.11.8 and kafka 0.9

Error:scalac: missing or invalid dependency detected while loading class file 'KafkaUnavailableException.class'.
Could not access type RuntimeException in package scala.package,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'KafkaUnavailableException.class' was compiled against an incompatible version of scala.package.

**Comment by manub** [comment]
Could this be related to #10 ?

**Comment by thesharpside** [comment]
I suspected it was related, however I changed my version from 2.11.8 to 2.11.7 and I still saw the build failure.

**Comment by manub** [comment]
v0.5.0 uses Scala 2.11.8 - have you tried to build against `0.4.3-kafka09` using Scala 2.11.7? Please let me know. Also, if you could paste your dependencies declaration that could be helpful.

**Comment by thesharpside** [comment]
After some hair-pulling, I finally stepped back and did a sanity check by running sbt compile from a terminal, which succeeded.  There seems to be some issue with IntelliJ and this setup.

dependencies used in project:

    "io.spray"            %%  "spray-can"     % sprayV,
    "io.spray"            %%  "spray-routing" % sprayV,
    "io.spray"            %%  "spray-testkit" % sprayV  % "test",
    "com.typesafe.akka"   %%  "akka-actor"    % akkaV,
    "com.typesafe.akka"   %%  "akka-testkit"  % akkaV   % "test",
    "org.specs2"          %%  "specs2-core"   % "2.3.11" % "test",
    "io.spray"            %%  "spray-json"    % "1.3.2",
    "com.typesafe.slick"  %%  "slick"          % "3.0.0",
    "org.postgresql"      % "postgresql"       % "9.3-1100-jdbc4",
    "org.apache.kafka" %% "kafka" % "0.9.0.0",
    "io.confluent"        % "kafka-avro-serializer" % "2.0.0",
    "com.julianpeeters"   %% "avrohugger-core" % "0.9.3",
    "joda-time"           % "joda-time"        % "2.9.3",
    "org.joda"            % "joda-convert"     % "1.2",
    "org.scalatest"       % "scalatest_2.11" % "2.2.1" % "test",
    "org.mockito"         % "mockito-core" % "1.9.5" % "test",
    "net.manub" %% "scalatest-embedded-kafka" % "0.5.0" % "test"

**Comment by manub** [comment]
This is strange. Although I'm more inclined to say that it could be a problem with the way IntelliJ interprets SBT dependencies.

**Comment by thesharpside** [comment]
I agree.  
I moved stuff around and tried different things and IntelliJ still interprets it as a build failure, but using sbt build is a workaround for the moment.

**Comment by manub** [comment]
I can keep this issue open for a while, in case anybody else experiences the same problem.

**Comment by thesharpside** [comment]
👍 
I'll update this thread if we are able to find a solution/cause

**Comment by thesharpside** [comment]
**Update**:  this is definitely a IntelliJ project file issue.  Other team members were able to check the same code and build successfully.  
I was able to resolve the error by re-creating the project file and manually setting the Module sources folders.

**Comment by manub** [comment]
Awesome, thanks for your feedback.
