### ISSUE TITLE
Documentation about Kafka version matching is incorrect

### ISSUE THREAD

**Issue by ches** [manub/scalatest-embedded-kafka#141]
The README states:

> Versions match the version of Kafka they're built against.

But, the 0.11.0 and 0.11.1 versions of scalatest-embedded-kafka were not built against those corresponding versions of Kafka:

- https://github.com/manub/scalatest-embedded-kafka/blob/v0.11.0/build.sbt#L5
- https://github.com/manub/scalatest-embedded-kafka/blob/v0.11.1/build.sbt#L5

These releases were in fact made before those Kafka versions existed.

I lost some time with binary incompatibilities on my classpath and checking whether I had transitive dependency conflicts needing exclusions, before realizing that it was actually scalatest-embedded-kafka bringing in 0.10 series Kafka, because I trusted the docs and overlooked it. Finally I realized versions like 0.16.0 are published, built against Kafka 0.11.

It'd be nice to update docs to mention that older versions mismatch, to spare others similar lost time. Also while we're at it, it'd be helpful to know what "nosr" means.

Thanks for the handy library!

**Comment by manub** [comment]
Thanks @ches - I've updated it now.
