### ISSUE TITLE
EmbeddedKafka.start(cfg) where zookeeper and kafka ports are determined

### ISSUE THREAD

**Issue by crankydillo** [manub/scalatest-embedded-kafka#143]
Hi,

I would like to use the manual start/stop methods of EmbeddedKafka along with having zookeeper and kafka ports determined by this library.  It seems like a trivial change made [here](https://github.com/manub/scalatest-embedded-kafka/blob/64d4eea3eb8042ba0a590332a8c16d2859cb340d/embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala#L64) involving reading the zookeeper port from the `factory` variable is all that's needed.  I don't mind creating a PR if you're OK with this change.

**Comment by manub** [comment]
Feel free to do so, keep in mind that ideally the old behaviour should be unchanged and the new behaviour should be happening only when calling the "new" way.

**Comment by crankydillo** [comment]
Thanks.  I was thinking the existing behavior would be changed though.  Is there ever a case, where we wouldn't want the port used by the zookeeper instance (created [here](https://github.com/manub/scalatest-embedded-kafka/blob/64d4eea3eb8042ba0a590332a8c16d2859cb340d/embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala#L61)) to be passed via `EmbeddedKafkaConfiguration` [here](https://github.com/manub/scalatest-embedded-kafka/blob/64d4eea3eb8042ba0a590332a8c16d2859cb340d/embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala#L64)?  In other words, I consider the existing behavior to be (very slightly:) buggy.

If someone was using the existing behavior to some end, they can always stick with the prior versions and/or open issues explaining their need:)

Anyhow, I will come up with a PR soon.
