### ISSUE TITLE
Decoupling scalatest from embedded kafka

### ISSUE THREAD

**Issue by crankydillo** [manub/scalatest-embedded-kafka#144]
I'm using this library from TestNG+Java tests.  I don't foresee a problem with ScalaTest being on the classpath; however, it would be nice if this was isolated.  Do you see a big problem breaking these apart?

**Comment by manub** [comment]
Using the `EmbeddedKafka` object would be fine, but some of the assertions and mixing the trait in won't be possible. It would require a bit of work which at the moment I cannot initiate, but I'd be happily look at a pull request.

We'd have also to change name to the project though... :)

**Comment by crankydillo** [comment]
Good to know.  RE project name change.. I know the code might be minimal, but it may make sense to have 2 projects.  Anyhow, you can decide that if I actually do come up with a PR:)
