### ISSUE TITLE
kafka.serializer.Encoder doesn't exist anymore in 2.0.0

### ISSUE THREAD

**Issue by TomLous** [manub/scalatest-embedded-kafka#156]
Running the `EmbeddedKafkaStreamsAllInOne` example I keep getting 

```
A needed class was not found. This could be due to an error in your runpath. Missing class: kafka/serializer/Encoder
java.lang.NoClassDefFoundError: kafka/serializer/Encoder
	at net.manub.embeddedkafka.Consumers.withStringConsumer(Consumers.scala:45)
```

I've noticed that I didn't have an Encoder class in my classpath.
I probably don't need it, but it's part of the Codecs object and probably why it fails

https://github.com/apache/kafka/tree/2.0/core/src/main/scala/kafka/serializer

**Comment by manub** [comment]
Which version of EmbeddedKafka you're using? Currently we don't support `2.0.0` but I'm planning to release a `2.0.0` version over the weekend.

**Comment by TomLous** [comment]
Oh sorry you are right. I'm using 2.0.0 with your 1.1.1 lib. I did manage to  work around by pulling the implicit serde out of the Codecs so it still works. Thanks!

**Comment by francescopellegrini** [comment]
Can we close this now?
