### ISSUE TITLE
Schema registry is not shutdown

### ISSUE THREAD

**Issue by 2m** [manub/scalatest-embedded-kafka#166]
When schema registry is created in `EmbeddedKafkaWithSchemaRegistry.start` it is not added to the `servers` global variable:

https://github.com/manub/scalatest-embedded-kafka/blob/64d4eea3eb8042ba0a590332a8c16d2859cb340d/schema-registry/src/main/scala/net.manub.embeddedkafka/schemaregistry/embeddedKafkaWithSchemaRegistry.scala#L157-L172

Therefore when `stop()` is called, the schema registry keeps running.

**Comment by francescopellegrini** [comment]
This was recently fixed in [the new WIP repo](https://github.com/embeddedkafka/embedded-kafka/commit/df98c8644612a21d2c986b106a443a0a679328ab), but thank you for reporting!

**Comment by 2m** [comment]
Ahh, great! Closing this ticket then.
