### ISSUE TITLE
Allow arbitrary Kafka properties in the configuration

### ISSUE THREAD

**Issue by chris-zen** [manub/scalatest-embedded-kafka#20]
I need to have topics automatically created with more than 1 partition to test something, but I couldn't figure out how to do it right now, because the `EmbeddedKafkaConfig` case class only allows to specify the ports for zookeeper and kafka.

What about having an extra field for arbitrary properties ? Something like:

```scala
case class EmbeddedKafkaConfig(
  kafkaPort: Int = 6001,
  zooKeeperPort: Int = 6000,
  kafkaServerProperties: Map[String, String] = Map.empty
)
```
You could check them and raise a warning or fail in case the user is overriding some of the ones you need to make it really embedded.

**Comment by manub** [comment]
Have you looked at the changes in #15? This looks very similar to what's been implemented. However currently custom provided properties gets overwritten by the default ones. Which property are you looking to set in particular?

I noticed though docs are lacking in this particular area. I'm going to update them.

**Comment by chris-zen** [comment]
That's exactly what I needed ! Thanks, looking forward for the next release.

I want to set `num.partitions` to 2, so new topics are created with 2 partitions by default.

**Comment by manub** [comment]
Thanks @chris-zen  - I've setup a gitter chat for the project. I'm gonna discuss release plans there - feel free to join!
