### ISSUE TITLE
Update to Kafka 0.10.0.0

### ISSUE THREAD

**Issue by max5599** [manub/scalatest-embedded-kafka#26]
Hi,
Thanks for you project it's very useful.
What about updating Kafka version to 0.10.0.0?

**Comment by max5599** [comment]
PR is pending for the update #27

**Comment by xelax** [comment]
When I use version 0.6.1 it with kafka 0.10 I get the following error:

[info] IntegrationSpec:
[info] Exception encountered when attempting to run a suite with class name: akka.kafka.scaladsl.IntegrationSpec *** ABORTED ***
[info]   java.lang.NoSuchMethodError: org.apache.kafka.common.config.AbstractConfig.<init>(Lorg/apache/kafka/common/config/ConfigDef;Ljava/util/Map;Ljava/lang/Boolean;)V
[info]   at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:714)
[info]   at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:716)
[info]   at net.manub.embeddedkafka.EmbeddedKafkaSupport$class.startKafka(EmbeddedKafka.scala:237)
[info]   at net.manub.embeddedkafka.EmbeddedKafka$.startKafka(EmbeddedKafka.scala:28)
[info]   at net.manub.embeddedkafka.EmbeddedKafka$.start(EmbeddedKafka.scala:40)
[info]   at akka.kafka.scaladsl.IntegrationSpec.beforeAll(IntegrationSpec.scala:45)
[info]   at org.scalatest.BeforeAndAfterAll$class.beforeAll(BeforeAndAfterAll.scala:187)
[info]   at akka.kafka.scaladsl.IntegrationSpec.beforeAll(IntegrationSpec.scala:33)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:253)
[info]   at akka.kafka.scaladsl.IntegrationSpec.run(IntegrationSpec.scala:33)

I wonder whether I am doing something wrong...

**Comment by xelax** [comment]
I think that the issue is that 0.6.1 was published with the dependency still on kafka 0.9.0.1 instead of 0.10.0.0:

https://mvnrepository.com/artifact/net.manub/scalatest-embedded-kafka_2.11/0.6.1

**Comment by manub** [comment]
Yes - use version `0.7.0` instead (just released).
