### ISSUE TITLE
Kafka Schema Registry

### ISSUE THREAD

**Issue by blbradley** [manub/scalatest-embedded-kafka#29]
Hello!

I'm experimenting with [Confluent's platform](http://docs.confluent.io/3.0.0/index.html). When using the Avro serializer from their platform, Kafka [Schema Registry](http://docs.confluent.io/3.0.0/schema-registry/docs/intro.html) becomes a required service (like ZooKeeper) for Kafka.

Would you be willing to accept submissions to this project in regard to the Schema Registry? Maybe start the Schema Registry if the serializer is the Avro serializer. It could be better off in another library, but I wanted to discuss that and how you feel about submissions.

Cheers!

**Comment by galarragas** [comment]
Hey @blbradley I think this would be a very good contribution 👍 You should consider the using the `MockSchemaRegistryClient` or the `ClusterTestHarness` ( the second option looks a bit more cumbersome)

**Comment by manub** [comment]
As the Schema Registry is not a core feature, I'd be OK to have it but provided that it's only enabled on demand and disabled by default. Feel free to submit a PR and we can discuss it.

**Comment by manub** [comment]
I think this can be closed now - please feel free to submit a PR and we'll take it from there.
