### ISSUE TITLE
Test hangs when running EmbeddedKafka

### ISSUE THREAD

**Issue by IoDmitri** [manub/scalatest-embedded-kafka#32]
Running EmbeddedKafka tests on a machine running Ubuntu 14.04 OS along with an Intel i7-4790 CPU @ 3.60GHz x 8 Processor, the test will hang. I have attached the full logs to this issue, but here are the 5 lines that keep being repeated, wondering if this is an issue related to Embedded Kafka at all. 

```
2016-08-11 13:15:47,553 - [DEBUG] - from org.apache.zookeeper.server.SessionTrackerImpl in ProcessT
Checking session 0x1000f61294e0000

2016-08-11 13:15:47,553 - [DEBUG] - from org.apache.zookeeper.server.FinalRequestProcessor in SyncT
Processing request:: sessionid:0x1000f61294e0000 type:ping cxid:0xfffffffffffffffe zxid:0xfffffffff

2016-08-11 13:15:47,553 - [DEBUG] - from org.apache.zookeeper.server.FinalRequestProcessor in SyncT
sessionid:0x1000f61294e0000 type:ping cxid:0xfffffffffffffffe zxid:0xfffffffffffffffe txntype:unkno

2016-08-11 13:15:47,553 - [TRACE] - from org.apache.zookeeper.server.NIOServerCnxn in SyncThread:0
Add a buffer to outgoingBuffers, sk sun.nio.ch.SelectionKeyImpl@2694758d is valid: true

2016-08-11 13:15:47,553 - [DEBUG] - from org.apache.zookeeper.ClientCnxn in pool-1-thread-1-ScalaTe
Got ping response for sessionid: 0x1000f61294e0000 after 1ms
```
[hanging.txt](https://github.com/manub/scalatest-embedded-kafka/files/413777/hanging.txt)

**Comment by manub** [comment]
Could you try to clone the project, run `sbt test` and see if it hangs?

**Comment by IoDmitri** [comment]
@manub Here are the logs from my colleague who's having issues running embeddedKafka. He went ahead and ran it on both an Ubnutu 14.04 and Ubnutu 16.04 machine respectively. 
[rohan_output_14.04.txt](https://github.com/manub/scalatest-embedded-kafka/files/450327/rohan_output_14.04.txt)
[rohan_output_16.04.txt](https://github.com/manub/scalatest-embedded-kafka/files/450328/rohan_output_16.04.txt)

**Comment by manub** [comment]
Which JDK are you using for both `14.04` and `16.04`?

**Comment by IoDmitri** [comment]
Here is the Java versions
Ubuntu 14.04 
```
$ java -version
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)
```

Ubuntu 16.04
```
$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```
There is some hanging reported on Ubuntu 16.04, with the following printout
```
[warn] org.apache.zookeeper.server.NIOServerCnxn - Exception causing close of session 0x0: Unreasonable length = 1340517
[warn] org.apache.zookeeper.server.NIOServerCnxn - Exception causing close of session 0x0: Unreasonable length = 1274981
[warn] org.apache.zookeeper.server.NIOServerCnxn - Exception causing close of session 0x0: Unreasonable length = 1340517
[warn] org.apache.zookeeper.server.NIOServerCnxn - Exception causing close of session 0x0: Unreasonable length = 1274981
...
```

**Comment by IoDmitri** [comment]
Here are some more Logs from Ubuntu 14.04
[rohan_output_14.04_java7.txt](https://github.com/manub/scalatest-embedded-kafka/files/450984/rohan_output_14.04_java7.txt)
[rohan_output_14.04_java8.txt](https://github.com/manub/scalatest-embedded-kafka/files/450985/rohan_output_14.04_java8.txt)

**Comment by manub** [comment]
I noticed some builds on CI hang as well sometimes. How you're using the library? Could you paste an example of the way you're writing your tests?

**Comment by manub** [comment]
Hi @IoDmitri - any news on this?

**Comment by manub** [comment]
Not able to replicate and missing feedback I'm going to close this issue. Feel free to reopen if needed.

**Comment by mewwts** [comment]
This might be completely off topic as I've not checked the logs here, but I've had tests hang forever when I've _failed to name a store_. Say I run a `stream.groupBy(something).count()` without an argument to `count()` and I have code that wants to query the the store of the count, it will just hang 😌
