### ISSUE TITLE
Remove dependency from log4j 1.x

### ISSUE THREAD

**Issue by hghina0** [manub/scalatest-embedded-kafka#36]
Apache released Log4j 2. This library still has dependency on log4 1.x and throws error ClassNotFoundException for log4j.Logger for non-maven user. If possible please switch to slf4j API.

**Comment by manub** [comment]
`log4j` is brought in transitively by Zookeeper.

I've just done some exploratory work (see branch https://github.com/manub/scalatest-embedded-kafka/tree/remove_log4j) and you can replace `log4j` with another logger implementation such as `slf4j` by using their bridges (http://www.slf4j.org/legacy.html). However I'm not sure this is the right thing to do by default in the library. It would be good to hear other people feelings about it.

**Comment by analytically** [comment]
Use `"org.slf4j" % "log4j-over-slf4j" % "1.7.21"` and `exclude("log4j", "log4j")`.

**Comment by manub** [comment]
Yeah - this could be embedded in the library as well but I'm not sure it would be the right thing to do. I'll need to think more about this.

**Comment by analytically** [comment]
I'd actually say it's not the right thing to do in scalatest-embedded-kafka. :-)

**Comment by manub** [comment]
Agreed. Closing this now as a solution to fix this on the application side has been provided. Thanks @analytically!
