### ISSUE TITLE
specs2 integration please

### ISSUE THREAD

**Issue by hghina0** [manub/scalatest-embedded-kafka#37]
I know this library designed for scalatest but I would appreciate if you can provide adaptor trait for specs2 support as well.

**Comment by manub** [comment]
That would be something people already asked me about - although the library necessarily wouldn't be called `scalatest-...`. I know very little about Specs2 myself - a PR would be welcome as I don't foresee having enough time in the short term to work on that.

**Comment by manub** [comment]
Superseded by #52.
