### ISSUE TITLE
Possibility to wait until kafka broker is completely stopped

### ISSUE THREAD

**Issue by eshepelyuk** [manub/scalatest-embedded-kafka#38]
Is it possible to call `awaitShutdown` on `KafkaServer` to ensure that broker is completely stopped ?

**Comment by manub** [comment]
Hi! Thanks for the suggestion - is it currently misbehaving?

**Comment by eshepelyuk** [comment]
Yes, sometimes it fails when several tests that launching `Kafka` are run.

**Comment by manub** [comment]
If you could provide me the stack trace I'll try to look at it.

**Comment by eshepelyuk** [comment]
Well, stack traces are different and now we don't have them to provide.

**Comment by manub** [comment]
I see. I'll have a look at this but it may take me a bit as I'm busy with other projects as well. If you want, you could submit a PR!

**Comment by manub** [comment]
Thanks for pointing this out @eshepelyuk !

**Comment by manub** [comment]
Releasing 0.8.1 now.
