### ISSUE TITLE
Reading KTables when testing Kafka Streams topologies

### ISSUE THREAD

**Issue by braadbaart** [manub/scalatest-embedded-kafka#49]
Using the KStreamBuilder DSL with custom serdes I found it impossible to consume internal Kafka streams topics that were built with the KTable abstraction. To be able to test intermediate steps in a streams topology, it would be great if KTables could also be consumed in the test runner.

**Comment by adamosloizou** [comment]
Hi @braadbaart thanks for the feedback.
It would be really helpful if you could share a the simplest code snippet that reproduces that case so that I can have a look.

Thanks!

**Comment by braadbaart** [comment]
Hi @adamosloizou, I'm afraid a simple snippet won't suffice to reproduce the case. The topology builder extends KStreamBuilder, uses a Kafka Streams`<T> KTable<K, T> aggregateByKey`, and custom domain objects for serializing and deserializing the KTable.

**Comment by braadbaart** [comment]
The KTables used in the topology are not listed as a source topic, and don't have either key or value serdes assigned. Attempting to consume these topics in a `runWithStreams` an embedded kafka test setup results in `org.apache.common.errors.TimeoutException: Timeout expired while fetching topic metadata` and `No such instance method: net.manub.embeddedkafka.ConsumerExtensions$ConsumerOps$$anonfun$getNextBatch$1.consumer` exceptions.

**Comment by braadbaart** [comment]
AFAICS, this could be the result of either missing configuration on my part or compaction of the KTable internal state. I was thinking that perhaps the issue could be solved by expanding the library's `ConsumerExtensions` to support reading changelogs.

**Comment by adamosloizou** [comment]
Hi @braadbaart, sorry for the delay. I am having a look this week and will let you know. Thanks again.

**Comment by braadbaart** [comment]
Thanks for the update, @adamosloizou ! I have some time to look into the issue myself today. Please keep me posted.

**Comment by adamosloizou** [comment]
@braadbaart please note that with the upgrade to Kafka `0.10.1.0` the Streams API has changed a bit. 
Can you please confirm that you are still seeing the problem with the new API?
Thanks.

**Comment by braadbaart** [comment]
I'm currently using kafka-client and kafka-streams 0.10.0.1 and scalatest-embedded-kafka 0.9.0.0. We're not planning to upgrade to kafka 0.10.1.0 just yet.

**Comment by braadbaart** [comment]
When overriding the kafka-client and kafka-streams libraries as per https://github.com/manub/scalatest-embedded-kafka/commit/a3aad9e211fb1932faae62b86d607f509d6fc564, I get the following error:
```java.lang.NoClassDefFoundError: org/apache/kafka/common/config/ConfigDef$ValidList
[info]   at kafka.log.LogConfig$.<init>(LogConfig.scala:276)
[info]   at kafka.log.LogConfig$.<clinit>(LogConfig.scala)
[info]   at kafka.server.KafkaConfig$.<init>(KafkaConfig.scala:270)
[info]   at kafka.server.KafkaConfig$.<clinit>(KafkaConfig.scala)
[info]   at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:795)
[info]   at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:797)
[info]   at net.manub.embeddedkafka.EmbeddedKafkaSupport$class.startKafka(EmbeddedKafka.scala:293)```

**Comment by manub** [comment]
This seems like a clash of dependencies issue. I'll try to investigate this - @kciesielski is this something you bumped in when trying to use `0.10.0.1` as you described in your changes?

**Comment by adamosloizou** [comment]
@braadbaart Have a look at an example at my [fork](https://github.com/adamosloizou/scalatest-embedded-kafka/blob/issue_49/kafka-streams/src/test/scala/net/manub/embeddedkafka/streams/ExampleKTableSpec.scala).
What's happening is that upon calling [aggregateByKey](https://github.com/adamosloizou/scalatest-embedded-kafka/blob/issue_49/kafka-streams/src/test/scala/net/manub/embeddedkafka/streams/ExampleKTableSpec.scala#L53) Kafka Streams create a "private" changelog topic that it is not supposed to be user visible because it prepends a UUID to the Table's name. This is the topic that I saw on my Kafka instance:
```
d2509f13-7585-4324-aa53-a8bd67ee012d-intermediateAggregatesTable-changelog
```

As such, I don't think it's expected for that topic to be testable unless you intervene, list the available topics and pick the one whose ending matches your table name.

If you do need to access the table then what you can do is use the `through()` call which will explicitly store the table to a visible topic and that way you can control its name and use it in your test assertions.

Have a look at the test and how it uses the `through()` call. It can then assert on both the intermediate table topic, `intermediateTopic` as well as the final output topic `toplevel-out`.

You shouldn't have to alter `ConsumerExtensions` for that.

Let me know how it goes!

**Comment by braadbaart** [comment]
Hi @adamosloizou thanks! Indeed, the internal topic is not meant to be consumed, but it can nevertheless be read from the command line in a running application like any other topic using the `console-consumer.sh` util.
I wanted to avoid creating an intermediate topic in the streams topology because that would mean altering the topology under test. The added value might not be worth the effort, though. De-materializing the KTable to a KStream indeed allows reading the data with the `.consumeLazily` method.

**Comment by adamosloizou** [comment]
@braadbaart I agree that from what I have seen so far, intercepting these "internal" topics is not worth it. If at some point you think they'd be of value, let me know, I'd be happy to discuss it further.

As for:
> De-materializing the KTable to a KStream indeed allows reading the data with the .consumeLazily method.

I am not sure what you mean by that.
There is no KTable to KStream conversion happening. That's how a KTable looks in Kafka. The topic's last value  per key is the the KTable's current value per key.
The rest is its history of updates. If we configure the table topic with compaction etc then the updates might go away and only keep the latest one. In principle though, this is exactly what a KTable topic looks like.

I hope this helps.

**Comment by braadbaart** [comment]
Ah, you're right - the `through` method creates another `KTable`.

**Comment by braadbaart** [comment]
Thanks again! I'll close the issue.

**Comment by adamosloizou** [comment]
Thank you @braadbaart for making me take a close look at the internals! Let us know if you come across anything else. Cheers!

**Comment by kciesielski** [comment]
@manub @braadbaart Looks like switching back like I mentioned in README is not possible, here's a PR which removes this info from documentation: #51
