### ISSUE TITLE
Investigate support for other test frameworks

### ISSUE THREAD

**Issue by manub** [manub/scalatest-embedded-kafka#52]
It seems pretty clear that this embedded-kafka could be used also with other test frameworks. 

A way to implement this is having a core module that embeds kafka, together with different libraries for different test frameworks (scalatest, specs2, ...). Probably this will require a library name change - and a bump to 1.0?

**Comment by reda-alaoui** [comment]
JUnit? :D

**Comment by manub** [comment]
I'm not planning to work on JUnit for this one so far, sorry!
