### ISSUE TITLE
Add possibility to override streams config in runStreams method

### ISSUE THREAD

**Issue by shadius** [manub/scalatest-embedded-kafka#68]
Hi,

TestStreamsConfig.streamConfig has a possibility to pass custom stream config as extraConfig parameter. Please add this param to EmbeddedKafkaStreams.runStreams that we can override some Stream config (like size of the local cache).

Thanks!

L.

**Comment by manub** [comment]
Hi L,

if you have time for submitting a pull request that'd be great, otherwise I'll look into it when I can.

**Comment by manub** [comment]
Fixed by #94
