### ISSUE TITLE
Update to Kafka 10.2

### ISSUE THREAD

**Issue by imduffy15** [manub/scalatest-embedded-kafka#69]
Kafka 10.2 passed voting over the weekend. JARs will be pushed to maven over the next coming days. The dependency for Kafka should be updated accordingly for testing with 10.2.

 http://markmail.org/message/xvay2452d73seduo

**Comment by manub** [comment]
This is fixed in v0.12.0, thanks!

**Comment by imduffy15** [comment]
Awesome. Thanks.
