### ISSUE TITLE
Make it possible to define maximum attempts/polling timeout in consume lazily

### ISSUE THREAD

**Issue by gigaSproule** [manub/scalatest-embedded-kafka#71]
We're using your library in a project, but noticing that the performance of our build slave is slow enough to have issues with consuming from Kafka, so we need the maximum number of attempts and polling timeout to be configurable. I've already started doing it (not really that big a change!), but just creating tests and will submit a pull request.

**Comment by manub** [comment]
Thanks @gigaSproule, looking forward to it!

**Comment by gigaSproule** [comment]
I've created the pull request, so if you could take a look, that would be great. I'm fairly new to the Scala world, so by all means, tell me if it's done in the wrong way.

**Comment by gigaSproule** [comment]
Seems like it's failed in Scala 2.11, so I will fix that.

**Comment by gigaSproule** [comment]
All fixed and merged in, so I guess this should be closed?

**Comment by manub** [comment]
Yes - thanks!
