### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by jmuth** [manub/scalatest-embedded-kafka#75]
Hi!

I would like to discard the logs produced by EmbeddedKafka (or at least to be allowed to chose the logging level.)

How can I do that?

Thx

**Comment by manub** [comment]
Pull in `log4j-over-slf4j` (see https://github.com/manub/scalatest-embedded-kafka/issues/36) and adjust your logging accordingly. Let me know if this helps.

**Comment by jmuth** [comment]
I couldn't do the job with `log4j-over-slf4j` but achieved it with your solution on commit a36ec5a2ce3e286a49eb887dd446c5a33e26575a

Thanks!
