### ISSUE TITLE
Possible fault in the README

### ISSUE THREAD

**Issue by akauppi** [manub/scalatest-embedded-kafka#8]
Hi,

in the section **Use without the withRunningKafka method**, it seems the code sample should use `EmbeddedKafka.start()`and such? Now it's awfully close to the earlier sample. Would you be so kind and check this? 

### Use without the `withRunningKafka` method

A `EmbeddedKafka` companion object is provided for usage without the `EmbeddedKafka` trait. Zookeeper and Kafka can be started an stopped in a programmatic way.

        class MySpec extends WordSpec {
    
        "runs with embedded kafka" should {

            withRunningKafka {
                // ... code goes here
            }
        
        }

**Comment by manub** [comment]
Good catch! Thanks for pointing this out. I'm going to update the docs.
