### ISSUE TITLE
withRunningKafka doesn't wait for a function body that returns a Future[Assertion]

### ISSUE THREAD

**Issue by jacobg** [manub/scalatest-embedded-kafka#83]
scalatest lets you write a test like the following:

```
class MySpec extends AsyncFlatSpec
  with Matchers
  with ScalaFutures {

  "this test" should "not finish until future completes" in {

    val future = Future {
      Thread.sleep(5000)
      "Done!"
    }

    future.map(value => assert(value == "Done!"))
  }
}
```

scalatest has the smarts to recognize that the closure returns a Future, will wait for it to complete, check that the future value is an Assertion, and finally verify that the Assertion is successful.

But if you run a similar test enclosed inside withRunningKafka, then Kafka shuts down before the future completes. If the test is testing functionality that asynchronously consumes from Kafka, then Kafka will be shut down before the consumer is complete.

A workaround is to implement beforeMethod and afterMethod, and use EmbeddedKafka.start() and EmbeddedKafka.stop() in those methods. That would then bind EmbeddedKafka's lifecycle to the lifecyle of the test.

But it would surely be great if EmbeddedKafka would recognize that the function body returns a future, and not shutdown until the future completes (or after a timeout).

Thanks!

**Comment by manub** [comment]
Hi @jacobg that's a very interesting issue indeed. I haven't looked really at the internals of Scalatest 3 for the AsyncSpecs so it would require me a bit more of digging into it. My time to work on this library right now is a bit limited so if you would like to provide a PR that'd be greatly appreciated, otherwise it may take me a bit to look into this but I'll try.

**Comment by francescopellegrini** [comment]
Loaner pattern and `Future`s [don't go along very well](https://stackoverflow.com/a/20769705)... A commons suggestion is to wrap the whole test in a `Future`, like this:

```scala
"this test" should {
  "not finish until future completes" in Future {
    withRunningKafka {
      Thread.sleep(5000)
      "Done!"
    }
  }.map(value => assert(value == "Done!"))
}
```

Could this solve your use case?

**Comment by francescopellegrini** [comment]
May we close this?
