### ISSUE TITLE
Sporadic org.apache.kafka.common.errors.TopicExistsException

### ISSUE THREAD

**Issue by TronPaul** [manub/scalatest-embedded-kafka#84]
I'm sporadically getting `TopicExistsException` on tests after the first test. I'm using `net.manub.embeddedkafka.streams.EmbeddedKafkaStreams#runStreams` to set up Kafka and Kafka Streams for the test. It seems the more topics I pass in for it to create the more likely the issue is to pop up. At 3 topics I saw it happen once. With 10 topics it happens occasionally.

I plan on coming up with a basic case that reproduces the issue and will post it here when I do. In the meantime, is there any methods that will let me access the Zookeeper the test methods use so I can try forcing cleanup? Looked around a bit, but couldn't find anything.

**Comment by manub** [comment]
Have you tried looking into the `AdminUtils` class given by Kafka? IIRC there are examples on how to connect to a zookeeper client in there.

**Comment by TronPaul** [comment]
Fairly certain I figured out the issue. I hadn't closed the Kafka producer I used after the test completed. I haven't seen the issue since I started closing producers.
