### ISSUE TITLE
Headers Support

### ISSUE THREAD

**Issue by baitmbarek** [manub/scalatest-embedded-kafka#93]
Hello,
Seems like Headers are not saved in the Kafka Server (which is a new feature of Kafka 0.11). Would it be possible to take a look ?
Edit : I guess the EmbeddedKafka.publishToKafka method should take an Map-like extra parameter for record headers and the "message" value in consumer method should handle the record headers in order to provide it in return.
Thanks ;)

**Comment by PiotrFras** [comment]
Instead of passing more and more parameters, consider exposing a method with kafka producer record as single parameter.
